lines = [
    "import React, { useEffect } from 'react';",
    "import { useNavigate } from 'react-router-dom';",
    "import {",
    "  FileSearch,",
    "  Sparkles,",
    "  ArrowRight,",
    "  Lightbulb,",
    "  CheckCircle2",
    "} from 'lucide-react';",
    "import { useAppContext } from '../context/AppContext';",
    "",
    "function ResultsPage() {",
    "  const navigate = useNavigate();",
    "  const { results, explanation } = useAppContext();",
    "  const displayExplanation = explanation || results?.explanation || '';",
    "",
    "  useEffect(() => {",
    "    if (!results) {",
    "      navigate('/analyze');",
    "    }",
    "  }, [results, navigate]);",
    "",
    "  if (!results) return null;",
    "",
    "  return (",
    '    <div className="max-w-4xl mx-auto py-8 animate-fadeIn">',
    '      <div className="flex items-center justify-between mb-8">',
    '        <div className="flex items-center gap-4">',
    '          <div className="w-12 h-12 rounded-2xl bg-indigo-600 flex items-center justify-center text-white shadow-lg">',
    '            <FileSearch size={24} />',
    '          </div>',
    '          <div>',
    '            <h1 className="text-3xl font-black text-slate-900">AI Explanation</h1>',
    '            <p className="text-slate-500 font-medium">AI-generated explanation of the detected bias.</p>',
    '          </div>',
    '        </div>',
    '        <button',
    "          onClick={() => navigate('/fix')}",
    '          className="flex items-center gap-2 px-8 py-3 bg-indigo-600 text-white rounded-2xl font-bold hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100"',
    '        >',
    '          Fix This Bias',
    '          <ArrowRight size={18} />',
    '        </button>',
    '      </div>',
    "",
    '      <div className="bg-white rounded-[2rem] border border-slate-100 shadow-xl overflow-hidden mb-8">',
    '        <div className="p-10">',
    '          <div className="flex items-start gap-4 mb-8">',
    '            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center flex-shrink-0 mt-1">',
    '              <Sparkles size={20} />',
    '            </div>',
    '            <div>',
    '              <h3 className="text-xl font-black text-slate-800 mb-4">AI Explanation</h3>',
    '              <div className="space-y-4 text-slate-600 leading-relaxed font-medium">',
    "                {displayExplanation.split('\\\\n').map((para, i) => (",
    '                  <p key={i}>{para}</p>',
    '                ))}",
    '                {!displayExplanation && <p>No detailed explanation available for this dataset.</p>}',
    '              </div>',
    '            </div>',
    '          </div>',
    "",
    '          <div className="border-t border-slate-100 pt-8">',
    '            <h4 className="text-lg font-black text-slate-800 mb-6 flex items-center gap-2">',
    '              <Lightbulb className="text-amber-500" />',
    '              Recommendations',
    '            </h4>',
    '            <ul className="grid gap-4">',
    '              {[',
    "                'Review input features for potential bias.',",
    "                'Consider collecting more diverse data.',",
    "                'Apply bias mitigation techniques.'",
    '              ].map((rec, i) => (',
    '                <li key={i} className="flex items-center gap-3 p-4 bg-slate-50 rounded-2xl border border-slate-100 group hover:border-indigo-200 transition-all">',
    '                  <CheckCircle2 size={18} className="text-emerald-500" />',
    '                  <span className="font-bold text-slate-700 group-hover:text-indigo-900 transition-colors">{rec}</span>',
    '                </li>',
    '              ))}',
    '            </ul>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    "",
    'export default ResultsPage;',
]

with open('frontend/src/pages/ResultsPage.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Written with balanced tags')
